---
########################################################
# Setting up ambari-server                             # 
# Configuring postgresql for hive on Redhat 7 family   #
########################################################

  - name: Configure Ambari server
    command: ambari-server setup -s  -j {{ JDK_HOME }}
    when: DOMAIN == 'local'

  - name: Configure Ambari server
    command: ambari-server setup -s
    when: DOMAIN != 'local'


  - name: Configure  hadoop-ipaddr method to trust in pg_hba.conf
    lineinfile:
     dest: /var/lib/pgsql/data/pg_hba.conf
     insertafter: "^# IPv4 local connections:"
     line: "host    all         all        {{ hostvars[item].ansible_default_ipv4.address }}/32        trust"
    with_items: groups['ODP_hadoop']
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

  - name: Configure local hive method to trust in pg_hba.conf
    lineinfile:
     dest: /var/lib/pgsql/data/pg_hba.conf
     insertbefore: "^# IPv4 local connections:"
     line: "local    all         hive                                                   trust"
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

  - name: Start postgresql
    service:
     name: postgresql
     state: restarted
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

  - name: Configure Ambari server for hive
    command: ambari-server setup --jdbc-db=postgres --jdbc-driver=/usr/share/java/postgresql-jdbc.jar
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

  - name: Start Ambari-Server
    service: name=ambari-server
           state=restarted enabled=yes



