---
################################
# Starting firewall / iptables # 
################################
- name: Start firewalld
  service: name=firewalld state=started
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['hadoop_hosts'] }}"


- name: Start iptables
  service: name=iptables state=started
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['hadoop_hosts'] }}"


- name: Start iptables-ubuntu
  shell: iptables-restore  /etc/iptables/rules.v4 
  when: "ansible_os_family == 'Debian'"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['hadoop_hosts'] }}"

